# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :test do
  gem 'guard-rspec', '4.7.3'
  gem 'rspec', '3.8.0'
  gem 'rubocop', '0.60.0'
end
